site_name: 无涯海
site_url: https://xiezg247.xyz/
repo_url: https://github.com/xiezg247/Capricorn/
docs_dir: docs
theme_dir: theme/updocs
copyright: Copyright &copy; 2018, xiezg247

pages:

- '文档首页': 'index.md'
- 'Flask源码剖析':
    - '简介': '笔记/专业技能/开发框架/FLASK/源码剖析/index.md'
    - '总览': '笔记/专业技能/开发框架/FLASK/源码剖析/Flask源码剖析(1)总览.md'
    - '简单应用': '笔记/专业技能/开发框架/FLASK/源码剖析/Flask源码剖析(2)简单应用.md'
    - '路由': '笔记/专业技能/开发框架/FLASK/源码剖析/Flask源码剖析(3)路由.md'
    - '上下文': '笔记/专业技能/开发框架/FLASK/源码剖析/Flask源码剖析(4)上下文.md'
    - '请求': '笔记/专业技能/开发框架/FLASK/源码剖析/Flask源码剖析(5)请求.md'
    - '响应': '笔记/专业技能/开发框架/FLASK/源码剖析/Flask源码剖析(6)响应.md'
    - 'session': '笔记/专业技能/开发框架/FLASK/源码剖析/Flask源码剖析(7)session.md'
    - '信号': '笔记/专业技能/开发框架/FLASK/源码剖析/Flask源码剖析(8)信号.md'
    - 'json解析': '笔记/专业技能/开发框架/FLASK/源码剖析/Flask源码剖析(9)json解析.md'
    - '视图': '笔记/专业技能/开发框架/FLASK/源码剖析/Flask源码剖析(10)视图.md'
    - '模板': '笔记/专业技能/开发框架/FLASK/源码剖析/Flask源码剖析(11)模板.md'
    - '配置': '笔记/专业技能/开发框架/FLASK/源码剖析/Flask源码剖析(12)配置.md'
    - '扩展': '笔记/专业技能/开发框架/FLASK/源码剖析/Flask源码剖析(13)扩展.md'
    - '测试': '笔记/专业技能/开发框架/FLASK/源码剖析/Flask源码剖析(14)测试.md'
    - '命令行接口': '笔记/专业技能/开发框架/FLASK/源码剖析/Flask源码剖析(15)命令行接口.md'
    - '辅助': '笔记/专业技能/开发框架/FLASK/源码剖析/Flask源码剖析(16)辅助.md'
    - '日志': '笔记/专业技能/开发框架/FLASK/源码剖析/Flask源码剖析(17)日志.md'
    - 'Debug辅助': '笔记/专业技能/开发框架/FLASK/源码剖析/Flask源码剖析(18)Debug辅助.md'
    - '兼容': '笔记/专业技能/开发框架/FLASK/源码剖析/Flask源码剖析(19)兼容.md'
    - '总结': '笔记/专业技能/开发框架/FLASK/源码剖析/Flask源码剖析(20)总结.md'

# Add permalink for sharing
markdown_extensions:
    - toc:
        permalink: True
